### PR TITLE
Version 2.12

### PR DESCRIPTION
**Pull request by HerrEurobeat**
Version 2.12

### CODE REVIEW

**Review by NikyHraz — CHANGES_REQUESTED** [review]
``.github/img/mesh.png

**Review by NikyHraz — COMMENTED** [review]
src/bot/commands/commentprofile.js

**Comment by HerrEurobeat** [comment]
Hey, thanks for engaging into the project, although I'm sadly unsure what you are trying to suggest.  
If you've got something that you would like to have changed, please clarify. Thanks!

**Comment by NikyHraz** [comment]
Now im in this autosteam creator And can take rank boost And commant

Dne st 9. 3. 2022 11:33 uživatel 3urobeat ***@***.***> napsal:

**Pull request merged**
